module.exports.config = {
  name: "imagine3",
  version: "1.0",
  role: 0,
  author: "Samuel Kâñèñgeè",
  description: "Search image but generated by AI",
  category: "Imagine",
  usages: "text - number of image to show",
  countdown: 5,
};

module.exports.onStart = async function({ api, event, args }) {
  const axios = require("axios");
  const fs = require("fs-extra");
  const request = require("request");

  const keySearch = args.join(" ");
  if (!keySearch.includes("-")) return api.sendMessage('Use: eg: mark Zuckerberg - 10', event.threadID, event.messageID);

  api.sendMessage("✅ Generating...", event.threadID, event.messageID);

  const keySearchs = keySearch.substr(0, keySearch.indexOf('-'));
  const numberSearch = keySearch.split("-").pop() || 6;

  const res = await axios.get(`https://free-api.ainz-sama101.repl.co/others/genimg?prompt=${encodeURIComponent(keySearchs)}`);
  const data = res.data.result;
  
  var num = 0;
  var imgData = [];

  for (var i = 0; i < parseInt(numberSearch); i++) {
    let path = __dirname + `/cache/${num+=1}.jpg`;
    let getDown = (await axios.get(`${data[i]}`, { responseType: 'arraybuffer' })).data;
    fs.writeFileSync(path, Buffer.from(getDown, 'utf-8'));
    imgData.push(fs.createReadStream(__dirname + `/cache/${num}.jpg`));
  }

  api.sendMessage({
    attachment: imgData,
    body: "Total image: " + data.length + "\nshowing " + numberSearch + ' generated images for ' + keySearchs + "\ngenerated by AI"
  }, event.threadID, event.messageID);

  for (let ii = 1; ii < parseInt(numberSearch); ii++) {
    fs.unlinkSync(__dirname + `/cache/${ii}.jpg`);
  }
};